FROM python:3.7.8-slim
ENV REDIS_PYTHON_VERSION  1.0

WORKDIR /code
COPY ./redis_python/ekg/redis_ekg_to_database_ems_dt15_t1.py /code

RUN python -m pip install \
        redis \
        mysql-connector-python
        
 CMD python ./redis_ekg_to_database_ems_dt15_t1.py



